### ISSUE TITLE
Travis CI with Azure Storage

### ISSUE THREAD

**Issue by D3v0nM** [MerryFairyTalesAD440/Builds#1]

**Comment by cjshaw** [comment]
Actual time spent 12 hours.

Used a python library I found on GitHub that Microsoft had linked out to on one of their tutorials.

I'm currently uploading one file with a specific name to blob storage, but that can change easily.
www.github.com/cjshaw/cloud-prac-storage-2349

**Comment by cjshaw** [comment]
[Here is a link to the wiki that documents my task](https://github.com/MerryFairyTalesAD440/Operations/wiki/Clint-Shaw)
