### ISSUE TITLE
Design Branch Structure

### ISSUE THREAD

**Issue by D3v0nM** [MerryFairyTalesAD440/Builds#2]

**Comment by DnlBell** [comment]
Finished by adding dev branches and some other test feature branches

**Comment by DnlBell** [comment]
Please review my wiki page for a diagram

https://github.com/MerryFairyTalesAD440/Operations/wiki/Daniel-Bell

**Comment by DnlBell** [comment]
I went ahead and made an example feature branch in the ui-ux repo called reactStarter

**Comment by DnlBell** [comment]
Branch building and documentation actually took about half an hour. Prepping an example feature branch took another hour.

https://github.com/MerryFairyTalesAD440/UX-UI/tree/reactStarter

**Comment by DnlBell** [comment]
Added rules for the dev and master branches in ux-ui and api
