### ISSUE TITLE
Design Travis Build for API

### ISSUE THREAD

**Issue by D3v0nM** [MerryFairyTalesAD440/Builds#3]

**Comment by ryanybrennan** [comment]
Spent a good amount of time troubleshooting Travis CI and connecting Visual Studio to Azure Functions. About 6 hours for the initial research.
Next Step: Connecting Travis CI to Azure. Estimated time: 2 hours. Time spend so far: 2.5 hours.

**Comment by ryanybrennan** [comment]
As far as I can tell, Travis CI is not able to connect to Azure Functions. Time spent so far: 7.5 hours. Groupmates able to find a workaround for Azure Storage, we'll see if there is one for Azure Functions.

**Comment by ryanybrennan** [comment]
Had some trouble with C#, but since Python worked well for Azure Storage, went down a bit of a rabbit-hole with Python, as in my computer is having version problems. Ended up sticking with C#. Time spent so far: 16 hours.

**Comment by ryanybrennan** [comment]
C# testing with Travis CI has proven challenging. Definitely know for sure Travis CI cannot connect to Azure Functions. Time spent total: ~20 hours.
https://github.com/MerryFairyTalesAD440/Operations/wiki/Ryan-Brennan

**Comment by toddysm** [comment]
Did you manage to get this working with Clint?

**Comment by ryanybrennan** [comment]
We are still working on it. We seem to be getting closer, we think.

**Comment by ryanybrennan** [comment]
Clint figured out a way to deploy to Azure Functions with Travis CI.
https://github.com/cjshaw/ad-cloud-func-test
