### ISSUE TITLE
Design Folder Structure

### ISSUE THREAD

**Issue by D3v0nM** [MerryFairyTalesAD440/Builds#4]

**Comment by Kading82** [comment]
Got it.

**Comment by DnlBell** [comment]
built a react starter folder

**Comment by Kading82** [comment]
Ended up taking roughly eight hours, still no clear path but general placeholders are in place based on examples from the internet and personal experience.

**Comment by Kading82** [comment]
Helpful link for designing folder structures: https://onextrapixel.com/building-web-apps-file-and-directory-structures/
