### ISSUE TITLE
Desgin Wiki

### ISSUE THREAD

**Issue by D3v0nM** [MerryFairyTalesAD440/Builds#5]

**Comment by ghost** [comment]
5+ hours

**Comment by ghost** [comment]
### Wiki Tasks

- [x] Convert swagger generated docs into markdown and add it to wiki page

- [x] Give everyone in devops team a wiki page

**Comment by ghost** [comment]
## Time

- Initial estimation: 5+ hours 

- Actual time: 3 hours
